name: automating github secret workflow...

on:
  push:
    branches: [ main ]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: DOCKER BUILDX
      uses: docker/setup-buildx-action@v3

    - name: LOGIN WITH SECRETS
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_SECRET_TOCKEN }}

    - name: FINALIZATION PUSHING IMAGE TO DOCKER
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64
        tags: |
          cainaidoo/corrtester:latest
          cainaidoo/corrtester:${{ github.run_number }}    
        cache-from: type=gha
        cache-to: type=gha,mode=max
